name: Build and upload

on:
  push:
    tags:
      - '*-emqx-*'  # Push events matching v*. e.g 1.0.0-emqx-1

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '28'
          rebar3-version: '3.25'
      - name: Build release binary
        run: |
          rebar3 escriptize
          cp _build/default/bin/elvis ./elvis
          ./elvis --version
      - name: Create release and upload binary
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$GITHUB_REF_NAME" ./elvis \
            --repo "$GITHUB_REPOSITORY" \
            --verify-tag \
            --title "$GITHUB_REF" \
            --notes "" \
            --prerelease=false
